### PR TITLE
Use munit diff logic

### PR DESCRIPTION
**Pull request by zainab-ali**
As part of #15 , we wish to improve the diff rendering of the `Comparison` trait by using a Myers diff implementation. [munit's Myers diff algorithm](https://github.com/scalameta/munit/pull/756) is a prime candidate.

As discussed on Discord, we prefer to vendor the diff logic than pull in an external dependency.

This PR is an experiment in vendoring.

Note that:
 - [x] tests must be updated.
 - [x] the `scala-diff` library is yet to be published.

### CODE REVIEW

**Comment by zainab-ali** [comment]
To summarize the discussions on this, there are two approaches we could take to improving the diff logic:
 - Vendor the munit diff code, as is done in the current changeset.
 - Pull in the [munit-diff](https://github.com/scalameta/munit/pull/756) library dependency.

I'm exploring pulling in the library dependency, but shading it such that users of weaver and munit are unaffected. Given that the lib is unlikely to change, but is on the same release cadence as munit, releases will also be excluded from Scala Steward.

**Comment by Baccata** [comment]
Changes look good 👍 

Do you have a rough idea of when munit-diff could be released ?

**Comment by zainab-ali** [comment]
Thanks! The PR has no obvious outstanding issues, so I expect it to be merged in the next few days. I'm not sure of the munit release cycle - @tgodzik may be able to comment.

**Comment by tgodzik** [comment]
Munit and munit-diff 1.0.0-RC1 is out. I also released manually for 0.4 Scala Native. Do let me know if it works!

**Review by Baccata — APPROVED** [review]

**Comment by Baccata** [comment]
Merging even if it depends on an RC, because it's shaded anyway, and because there's still a little bit of work to be done before an actual release of weaver, which may give munit enough time for a 1.0.0 release

**Pull request merged**
